### ISSUE TITLE
menu bar 

### ISSUE THREAD

**Issue by Vanesh37** [officialzubairansari/e-karobar-website#1]
menu bar didn't show all the options except home button until unless we click on blank space or scroll the pages down 

https://github.com/officialzubairansari/e-karobar-website/assets/110464597/46526ed3-3891-494a-9e62-1a343977d697

**Comment by officialzubairansari** [comment]
Thank you @Vanesh37 for pointing out this, we are resolving this <3

**Comment by officialzubairansari** [comment]
And one last thing, you you wants to contribute for Hacktober fest, please to a little change on readme file etc, so then we can merger your pull request.
