### ISSUE TITLE
Footer social media links opening on the same tab as the current tab

### ISSUE THREAD

**Issue by tmsagarofficial** [officialzubairansari/e-karobar-website#3]
I would like to point it out that social media links in the footer of the website are opening in the same tab as of the current tab . THis will hinder the user Experience . And hence should be made such that links open in a separate tab.
<img width="141" alt="image" src="https://github.com/officialzubairansari/e-karobar-website/assets/110724849/0ec8e194-83d1-4af0-9a59-c82de430a4b7">

Pls assign this issue to me so that I can work on this under hacktoberfest. @officialzubairansari

**Comment by officialzubairansari** [comment]
@tmsagarofficial Thank you soo much for pointing out this problem, Yes please you can can on this under hacktober fest, 
please for the repository, then change the content as you want then send pull request, we will merge it immediatly.

**Comment by officialzubairansari** [comment]
and please let me know personally if you need any guidance about doing under hacktoberfest, I will guide you too.

**Comment by tmsagarofficial** [comment]
Thanks, @officialzubairansari.

Will start working on this issue. Will let u know if I get stuck or anything.

> @tmsagarofficial Thank you soo much for pointing out this problem, Yes please you can can on this under hacktober fest, please for the repository, then change the content as you want then send pull request, we will merge it immediatly.

**Comment by officialzubairansari** [comment]
ok ok sure, Here is my WhatsApp no +923222138989 you can directly reach me.

**Comment by officialzubairansari** [comment]
let me share you one great thing, 
Know you don't need to clone the whole repository into you machine.
1) just fork the repository 
2) replace .con on the repo link with dev - 
your link: https://github.com/your-name/e-karobar-website 
after replaced https://github.dev/your-name/e-karobar-website 

vs code will automatically opened on you browser where you can make changes directly, the in option you will get pull request button on corner. 

That's it

**Comment by tmsagarofficial** [comment]
Hey i need to change only in this file right ? resources\views\index.blade.php

**Comment by officialzubairansari** [comment]
yes exactly,

**Comment by officialzubairansari** [comment]
Hey listen, let me give you a github badge, 
create a new issue and let me know within 5 mint, I will also close the issue within five mint so you will get a github badge as well

**Comment by tmsagarofficial** [comment]
OKay

a new issue on what?

**Comment by officialzubairansari** [comment]
just on random issue, which is even not exist

**Comment by officialzubairansari** [comment]
yes it is done, you will get badge within some minutes of process, I already share my whatsAoo contact no where you can reach me

**Comment by tmsagarofficial** [comment]
Hey did you add the labels for Hacktoberfest? @officialzubairansari

**Comment by tmsagarofficial** [comment]
> Hey did you add the labels for Hacktoberfest? @officialzubairansari

Pls add hacktoberfest-accpeted labels @officialzubairansari 😅

**Comment by officialzubairansari** [comment]
yes I did,
