### ISSUE TITLE
Update link in training button of hero section required

### ISSUE THREAD

**Issue by tmsagarofficial** [officialzubairansari/e-karobar-website#7]
I would like to point out that training links in the hero section of the website are open in the same tab as the current tab. This will hinder the user Experience. Hence should be made such that the link opens in a separate tab.
image
![image](https://github.com/officialzubairansari/e-karobar-website/assets/110724849/a7fcec83-0739-4fc8-ad68-89e2a65bf86c)

Pls assign this issue to me so that I can work on this under hacktoberfest. @officialzubairansari

**Comment by VivekGuruduttK28** [comment]
I would like to take this up @officialzubairansari . Will raise a PR soon
