### ISSUE TITLE
Update of favicon required

### ISSUE THREAD

**Issue by tmsagarofficial** [officialzubairansari/e-karobar-website#8]
It seems that the current favicon doesn't exactly look nice in dark themed browsers and it looks like below
<img width="27" alt="image" src="https://github.com/officialzubairansari/e-karobar-website/assets/110724849/31053830-d858-4d57-8c2b-be5449197ca7">

hence updating the favicon and making sure that these white corners are made transparent so that these will work fine on any kind of browsers.

Pls assign this issue to me so that I can work on this under hacktoberfest. @officialzubairansari

**Comment by officialzubairansari** [comment]
Yes sure please go for it, do let me know if you need anything.

**Comment by tmsagarofficial** [comment]
Hey did u just close this issue? @officialzubairansari
