### ISSUE TITLE
Footer link update required

### ISSUE THREAD

**Issue by vinay-s36** [officialzubairansari/e-karobar-website#9]
Hi @officialzubairansari there is issue in 'location' in the footer as it is not pointing the exact location.

Please assign this issue to me so that I can work on this under hacktoberfest.

![locationissue](https://github.com/officialzubairansari/e-karobar-website/assets/124019116/5c4a4d28-0c9e-4683-ae1c-93d7c4cbc484)

**Comment by officialzubairansari** [comment]
Yes sure you can go for it, 
Do let us know if you need any information.
